- name: Configuração da VM
  hosts: vm
  become: yes

  tasks:
    - name: Role Apache
      include_role:
          name: geerlingguy.apache

    - name: Inclui a role curso
      include_role: 
          name: curso


